name: calculateur_solaire
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter_html: ^3.0.0-beta.2 
  flutter:
    sdk: flutter
  http: ^1.2.0 
  flutter_localizations:
    sdk: flutter
  # UI / routing / state / network / device
  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0

  # PDF / partage / intents / localisation / prefs / secure storage
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"  # <-- ton image source
  min_sdk_android: 21 # nécessaire pour Android

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
